name: calorie_tracker
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  firebase_core: ^2.13.1
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  google_sign_in: ^6.1.4
  openfoodfacts:
    git:
      url: https://github.com/ketanchoyal/openfoodfacts-dart.git
      ref: product-status-enum
  json_theme: ^4.0.0
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.5
  ai_barcode_scanner: ^0.0.6
  flutter_form_bloc: ^0.30.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_settings_ui: ^2.0.1
  flutter_hooks: ^0.18.6
  swipeable_tile: ^2.0.0+3
  adaptive_dialog: 1.9.0-no-macos.2
  wolt_modal_sheet: ^0.0.4
  auto_size_text_field: ^2.2.1
  health:
    path: packages/health
  custom_radio_grouped_button: ^2.2.0
  drop_down_list:
    path: packages/drop_down_list

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0+1
  freezed: ^2.3.5
  build_runner: ^2.4.5
  flutter_gen_runner:
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/theme/theme_light.json
    - assets/theme/theme_dark.json
    - shorebird.yaml

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
