name: calorie_tracker
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  firebase_core: ^2.12.0
  cloud_firestore: ^4.7.0
  firebase_auth: ^4.6.0
  google_sign_in: ^6.1.0
  openfoodfacts: ^1.17.0
  json_theme: ^4.0.0
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.5
  flutter_barcode_scanner: ^2.0.0
  flutter_form_bloc: ^0.30.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  flutter_settings_ui: ^2.0.1
  flutter_hooks: ^0.18.6
  swipeable_tile: ^2.0.0+3
  adaptive_dialog: 1.9.0-no-macos.2
  health:
    path: packages/health
  custom_radio_grouped_button: ^2.2.0
  drop_down_list:
    path: packages/drop_down_list

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1
  freezed: ^2.3.4
  build_runner: ^2.4.4
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/theme/theme_light.json
    - assets/theme/theme_dark.json

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
