name: calorie_tracker
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  firebase_core: ^1.17.0
  openfoodfacts: ^1.17.0
  json_theme: ^4.0.0
  font_awesome_flutter: ^10.1.0
  flutter_barcode_scanner: ^2.0.0
  flutter_form_bloc: ^0.30.1
  freezed_annotation: ^2.0.3
  json_annotation: ^4.5.0
  flutter_settings_ui: ^2.0.1
  drop_down_list:
    path: packages/drop_down_list

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0
  freezed: ^2.0.3+1
  build_runner: ^2.1.11
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/theme/theme_light.json
    - assets/theme/theme_dark.json

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
